'use strict';
// Search keywords for the most important pages, keyed by URL path.
//   primary:   the main phrase people type; it leads the title, H1 and description
//   secondary: close variants (other spellings, "converter", "online free")
//   longtail:  longer searches with a specific need; the page content should answer them
// Pages not listed here fall back to the patterns in registry metadata.
// Priority (1 = highest) is an estimate of search demand, used to order indexing requests.

module.exports = {
  // ---------- Home ----------
  '/': { priority: 1, primary: 'file converter',
    secondary: ['free file converter', 'online file converter', 'convert files online', 'file converter online free'],
    longtail: ['convert any file online free', 'free file converter no sign up', 'file converter without watermark', 'convert video audio image document online'] },

  // ---------- Images ----------
  '/jpg-to-png': { priority: 1, primary: 'jpg to png',
    secondary: ['jpg to png converter', 'convert jpg to png', 'jpeg to png', 'jpg to png online free'],
    longtail: ['change jpg to png without losing quality', 'convert multiple jpg to png at once', 'jpg to png high quality', 'how to convert jpg to png on phone'] },
  '/png-to-jpg': { priority: 1, primary: 'png to jpg',
    secondary: ['png to jpg converter', 'convert png to jpg', 'png to jpeg', 'png to jpg online free'],
    longtail: ['png to jpg without losing quality', 'png to jpg white background', 'reduce png size by converting to jpg', 'batch convert png to jpg'] },
  '/webp-to-jpg': { priority: 1, primary: 'webp to jpg',
    secondary: ['webp to jpg converter', 'convert webp to jpg', 'webp to jpeg', 'webp to jpg online free'],
    longtail: ['how to open webp image', 'save webp as jpg', 'webp to jpg batch converter', 'webp to jpg high quality'] },
  '/webp-to-png': { priority: 1, primary: 'webp to png',
    secondary: ['webp to png converter', 'convert webp to png', 'webp to png online free'],
    longtail: ['webp to png transparent background', 'save webp as png', 'batch convert webp to png', 'webp to png without losing quality'] },
  '/jpg-to-webp': { priority: 2, primary: 'jpg to webp',
    secondary: ['jpg to webp converter', 'convert jpg to webp', 'jpeg to webp'],
    longtail: ['convert images to webp for website', 'jpg to webp bulk converter', 'reduce image size for website', 'jpg to webp without losing quality'] },
  '/png-to-webp': { priority: 2, primary: 'png to webp',
    secondary: ['png to webp converter', 'convert png to webp', 'png to webp online'],
    longtail: ['png to webp keep transparency', 'convert png to webp for wordpress', 'png to webp bulk', 'png to webp lossless'] },
  '/heic-to-jpg': { priority: 1, primary: 'heic to jpg',
    secondary: ['heic to jpg converter', 'convert heic to jpg', 'heic to jpeg', 'heic to jpg online free'],
    longtail: ['how to open iphone photos on windows', 'convert iphone photos to jpg', 'heic to jpg multiple files', 'heic to jpg without losing quality'] },
  '/heic-to-png': { priority: 2, primary: 'heic to png',
    secondary: ['heic to png converter', 'convert heic to png', 'heic to png online'],
    longtail: ['iphone photo to png', 'heic to png free no sign up', 'convert heic to png on windows'] },
  '/avif-to-jpg': { priority: 2, primary: 'avif to jpg',
    secondary: ['avif to jpg converter', 'convert avif to jpg', 'avif to jpeg'],
    longtail: ['how to open avif file', 'save avif image as jpg', 'avif to jpg online free'] },
  '/avif-to-png': { priority: 3, primary: 'avif to png',
    secondary: ['avif to png converter', 'convert avif to png'],
    longtail: ['avif to png transparent', 'avif to png online free'] },
  '/gif-to-webp': { priority: 3, primary: 'gif to webp',
    secondary: ['gif to webp converter', 'convert gif to webp', 'animated gif to webp'],
    longtail: ['reduce gif size with webp', 'animated webp from gif', 'gif to webp keep animation'] },
  '/svg-to-png': { priority: 1, primary: 'svg to png',
    secondary: ['svg to png converter', 'convert svg to png', 'svg to png online'],
    longtail: ['svg to png transparent background', 'svg to png high resolution', 'svg to png free no sign up'] },
  '/png-to-ico': { priority: 2, primary: 'png to ico',
    secondary: ['png to ico converter', 'convert png to ico', 'favicon generator from png'],
    longtail: ['make favicon from png', 'png to ico for windows icon', 'png to ico multiple sizes'] },
  '/tiff-to-jpg': { priority: 2, primary: 'tiff to jpg',
    secondary: ['tif to jpg', 'tiff to jpg converter', 'convert tiff to jpg', 'tiff to jpeg'],
    longtail: ['convert scanned tiff to jpg', 'tiff to jpg online free', 'reduce tiff file size'] },
  '/bmp-to-jpg': { priority: 3, primary: 'bmp to jpg',
    secondary: ['bmp to jpg converter', 'convert bmp to jpg', 'bmp to jpeg'],
    longtail: ['bmp to jpg online free', 'reduce bmp file size'] },
  '/jfif-to-jpg': { priority: 2, primary: 'jfif to jpg',
    secondary: ['jfif to jpg converter', 'convert jfif to jpg', 'jfif to jpeg'],
    longtail: ['what is jfif file', 'change jfif to jpg', 'jfif to jpg online free'] },

  // ---------- PDF ----------
  '/jpg-to-pdf': { priority: 1, primary: 'jpg to pdf',
    secondary: ['jpg to pdf converter', 'convert jpg to pdf', 'image to pdf', 'jpeg to pdf'],
    longtail: ['combine jpg into one pdf', 'jpg to pdf multiple pages', 'photo to pdf online free', 'jpg to pdf without watermark'] },
  '/png-to-pdf': { priority: 2, primary: 'png to pdf',
    secondary: ['png to pdf converter', 'convert png to pdf', 'image to pdf'],
    longtail: ['screenshot to pdf', 'png to pdf multiple files', 'png to pdf online free'] },
  '/pdf-to-jpg': { priority: 1, primary: 'pdf to jpg',
    secondary: ['pdf to jpg converter', 'convert pdf to jpg', 'pdf to image', 'pdf to jpeg'],
    longtail: ['pdf to jpg high quality', 'save pdf pages as images', 'pdf to jpg all pages', 'pdf to jpg online free'] },
  '/pdf-to-png': { priority: 2, primary: 'pdf to png',
    secondary: ['pdf to png converter', 'convert pdf to png', 'pdf to image'],
    longtail: ['pdf to png high resolution', 'pdf page to png', 'pdf to png online free'] },
  '/pdf-to-docx': { priority: 1, primary: 'pdf to word',
    secondary: ['pdf to docx', 'pdf to word converter', 'convert pdf to word', 'pdf to doc'],
    longtail: ['pdf to word editable', 'pdf to word free without email', 'convert pdf to word keep formatting', 'pdf to word online free'] },
  '/docx-to-pdf': { priority: 1, primary: 'word to pdf',
    secondary: ['docx to pdf', 'word to pdf converter', 'convert word to pdf', 'doc to pdf'],
    longtail: ['word to pdf online free', 'convert docx to pdf keep formatting', 'save word document as pdf', 'word to pdf without watermark'] },
  '/doc-to-pdf': { priority: 2, primary: 'doc to pdf',
    secondary: ['doc to pdf converter', 'convert doc to pdf', 'old word file to pdf'],
    longtail: ['doc to pdf online free', 'convert word 97-2003 to pdf'] },
  '/doc-to-docx': { priority: 3, primary: 'doc to docx',
    secondary: ['doc to docx converter', 'convert doc to docx'],
    longtail: ['open old word documents', 'doc to docx online free'] },
  '/xlsx-to-pdf': { priority: 2, primary: 'excel to pdf',
    secondary: ['xlsx to pdf', 'excel to pdf converter', 'convert excel to pdf'],
    longtail: ['excel to pdf fit to page', 'excel to pdf online free', 'save spreadsheet as pdf'] },
  '/pptx-to-pdf': { priority: 2, primary: 'ppt to pdf',
    secondary: ['pptx to pdf', 'powerpoint to pdf', 'convert ppt to pdf'],
    longtail: ['powerpoint to pdf online free', 'presentation to pdf', 'pptx to pdf keep fonts'] },
  '/pdf-to-txt': { priority: 3, primary: 'pdf to text',
    secondary: ['pdf to txt', 'pdf to text converter', 'extract text from pdf'],
    longtail: ['copy text from pdf', 'pdf to txt online free'] },
  '/epub-to-pdf': { priority: 2, primary: 'epub to pdf',
    secondary: ['epub to pdf converter', 'convert epub to pdf'],
    longtail: ['ebook to pdf', 'epub to pdf online free', 'print epub book'] },

  // ---------- Spreadsheets ----------
  '/csv-to-xlsx': { priority: 2, primary: 'csv to excel',
    secondary: ['csv to xlsx', 'csv to excel converter', 'convert csv to excel'],
    longtail: ['open csv in excel correctly', 'csv to xlsx online free'] },
  '/xlsx-to-csv': { priority: 2, primary: 'excel to csv',
    secondary: ['xlsx to csv', 'excel to csv converter', 'convert excel to csv'],
    longtail: ['xlsx to csv online free', 'save excel as csv utf-8'] },

  // ---------- Video ----------
  '/mp4-to-mp3': { priority: 1, primary: 'mp4 to mp3',
    secondary: ['mp4 to mp3 converter', 'convert mp4 to mp3', 'video to mp3', 'video to audio converter'],
    longtail: ['extract audio from video', 'mp4 to mp3 high quality', 'mp4 to mp3 online free', 'video to mp3 without software'] },
  '/mov-to-mp4': { priority: 1, primary: 'mov to mp4',
    secondary: ['mov to mp4 converter', 'convert mov to mp4', 'iphone video to mp4'],
    longtail: ['mov to mp4 online free', 'mov to mp4 without losing quality', 'convert quicktime to mp4'] },
  '/mkv-to-mp4': { priority: 2, primary: 'mkv to mp4',
    secondary: ['mkv to mp4 converter', 'convert mkv to mp4'],
    longtail: ['mkv to mp4 online free', 'mkv to mp4 without losing quality', 'play mkv on phone'] },
  '/webm-to-mp4': { priority: 2, primary: 'webm to mp4',
    secondary: ['webm to mp4 converter', 'convert webm to mp4'],
    longtail: ['webm to mp4 online free', 'screen recording webm to mp4'] },
  '/avi-to-mp4': { priority: 2, primary: 'avi to mp4',
    secondary: ['avi to mp4 converter', 'convert avi to mp4'],
    longtail: ['avi to mp4 online free', 'old video to mp4'] },
  '/mp4-to-gif': { priority: 2, primary: 'mp4 to gif',
    secondary: ['video to gif', 'mp4 to gif converter', 'convert mp4 to gif'],
    longtail: ['make gif from video', 'video to gif online free', 'mp4 to gif high quality'] },
  '/gif-to-mp4': { priority: 3, primary: 'gif to mp4',
    secondary: ['gif to mp4 converter', 'convert gif to mp4', 'gif to video'],
    longtail: ['gif to mp4 for instagram', 'gif to mp4 online free'] },

  // ---------- Audio ----------
  '/wav-to-mp3': { priority: 2, primary: 'wav to mp3',
    secondary: ['wav to mp3 converter', 'convert wav to mp3'],
    longtail: ['wav to mp3 320kbps', 'wav to mp3 online free', 'reduce wav file size'] },
  '/m4a-to-mp3': { priority: 2, primary: 'm4a to mp3',
    secondary: ['m4a to mp3 converter', 'convert m4a to mp3'],
    longtail: ['iphone voice memo to mp3', 'm4a to mp3 online free', 'whatsapp audio to mp3'] },
  '/flac-to-mp3': { priority: 3, primary: 'flac to mp3',
    secondary: ['flac to mp3 converter', 'convert flac to mp3'],
    longtail: ['flac to mp3 320kbps', 'flac to mp3 online free'] },
  '/ogg-to-mp3': { priority: 3, primary: 'ogg to mp3',
    secondary: ['ogg to mp3 converter', 'convert ogg to mp3', 'opus to mp3'],
    longtail: ['whatsapp voice note to mp3', 'ogg to mp3 online free'] },

  // ---------- Ebooks ----------
  '/epub-to-mobi': { priority: 3, primary: 'epub to mobi',
    secondary: ['epub to mobi converter', 'convert epub to mobi', 'epub to kindle'],
    longtail: ['epub to mobi online free', 'read epub on kindle'] },
  '/mobi-to-epub': { priority: 3, primary: 'mobi to epub',
    secondary: ['mobi to epub converter', 'convert mobi to epub'],
    longtail: ['kindle book to epub', 'mobi to epub online free'] },

  // ---------- Fonts ----------
  '/ttf-to-woff2': { priority: 3, primary: 'ttf to woff2',
    secondary: ['ttf to woff2 converter', 'convert ttf to woff2', 'web font converter'],
    longtail: ['convert font for website', 'ttf to woff2 online free'] },
  '/woff2-to-ttf': { priority: 3, primary: 'woff2 to ttf',
    secondary: ['woff2 to ttf converter', 'convert woff2 to ttf'],
    longtail: ['install web font on windows', 'woff2 to ttf online free'] },

  // ---------- Compress ----------
  '/compress-jpg': { priority: 1, primary: 'compress jpg',
    secondary: ['jpg compressor', 'compress jpeg', 'reduce jpg size', 'compress image'],
    longtail: ['compress jpg to 100kb', 'compress jpg to 50kb', 'reduce photo size online', 'compress image without losing quality'] },
  '/compress-png': { priority: 2, primary: 'compress png',
    secondary: ['png compressor', 'reduce png size', 'png optimizer'],
    longtail: ['compress png without losing quality', 'compress png keep transparency', 'reduce png file size online'] },
  '/compress-pdf': { priority: 1, primary: 'compress pdf',
    secondary: ['pdf compressor', 'reduce pdf size', 'pdf size reducer'],
    longtail: ['compress pdf to 1mb', 'compress pdf for email', 'reduce pdf size online free', 'compress pdf without losing quality'] },
  '/compress-webp': { priority: 3, primary: 'compress webp',
    secondary: ['webp compressor', 'reduce webp size'],
    longtail: ['compress webp online free'] },
  '/compress-gif': { priority: 2, primary: 'compress gif',
    secondary: ['gif compressor', 'reduce gif size'],
    longtail: ['compress gif for discord', 'reduce gif file size online'] },
  '/compress-avif': { priority: 3, primary: 'compress avif',
    secondary: ['avif compressor', 'reduce avif size'],
    longtail: ['compress avif online free'] },
  '/compress-tiff': { priority: 3, primary: 'compress tiff',
    secondary: ['tiff compressor', 'reduce tiff size'],
    longtail: ['compress scanned tiff online'] },

  // ---------- Categories ----------
  '/image-converter': { priority: 1, primary: 'image converter',
    secondary: ['photo converter', 'image format converter', 'convert image online'],
    longtail: ['free image converter online', 'convert image to jpg', 'convert image to png'] },
  '/video-converter': { priority: 1, primary: 'video converter',
    secondary: ['online video converter', 'convert video online', 'video format converter'],
    longtail: ['free video converter no watermark', 'convert video to mp4 online'] },
  '/audio-converter': { priority: 2, primary: 'audio converter',
    secondary: ['online audio converter', 'convert audio online', 'mp3 converter'],
    longtail: ['convert audio to mp3 online free', 'free audio converter no sign up'] },
  '/document-converter': { priority: 2, primary: 'document converter',
    secondary: ['online document converter', 'convert documents online', 'word converter'],
    longtail: ['convert document to pdf online free'] },
  '/pdf-converter': { priority: 1, primary: 'pdf converter',
    secondary: ['online pdf converter', 'convert pdf', 'pdf converter free'],
    longtail: ['pdf converter without watermark', 'convert pdf to word excel jpg'] },
  '/ebook-converter': { priority: 3, primary: 'ebook converter',
    secondary: ['epub converter', 'online ebook converter'],
    longtail: ['convert ebook to pdf', 'convert ebook for kindle'] },
  '/font-converter': { priority: 3, primary: 'font converter',
    secondary: ['web font converter', 'ttf converter', 'woff converter'],
    longtail: ['convert font to woff2 online'] },
};
