'use strict';
// Search keywords for the most important pages, keyed by URL path.
//   primary:   the main phrase people type; it leads the title, H1 and description
//   secondary: close variants (other spellings, "converter", "online free")
//   longtail:  longer searches with a specific need; the page content should answer them
//   more:      further long-tail variations (device, platform, size, purpose)
//   lsi:       related words a good page on the topic naturally uses; for writing content, not for repeating
// Pages not listed here fall back to the patterns in registry metadata.
// Priority (1 = highest) is an estimate of search demand, used to order indexing requests.

module.exports = {
  // ---------- Home ----------
  '/': { priority: 1, primary: 'file converter',
    secondary: ['free file converter', 'online file converter', 'convert files online', 'file converter online free'],
    longtail: ['convert any file online free', 'free file converter no sign up', 'file converter without watermark', 'convert video audio image document online'],
    more: ['best free online file converter', 'convert files without installing software', 'online converter for pdf word jpg mp4', 'file converter for mobile', 'convert files online without email', 'safe online file converter', 'convert file format online'],
    lsi: ['file format', 'convert documents', 'image formats', 'video formats', 'audio files', 'batch conversion', 'online tool', 'no installation', 'browser based', 'free converter'] },

  // ---------- Images ----------
  '/jpg-to-png': { priority: 1, primary: 'jpg to png',
    secondary: ['jpg to png converter', 'convert jpg to png', 'jpeg to png', 'jpg to png online free'],
    longtail: ['change jpg to png without losing quality', 'convert multiple jpg to png at once', 'jpg to png high quality', 'how to convert jpg to png on phone'],
    more: ['jpg to png converter no download', 'convert jpeg image to png format', 'jpg to png for editing', 'turn jpg into png', 'jpg to png bulk converter', 'jpg to png converter for pc', 'jpg to png on iphone', 'jpg to png on android'],
    lsi: ['lossless', 'image quality', 'pixels', 'compression artifacts', 'transparency', 'raster image', 'photo editing', 'file extension', 'image format'],
    faq: [['How do I convert JPG to PNG on my phone?', 'Open this page in your phone browser, tap Select File and pick the photos from your gallery. The PNG files download straight to your phone, with nothing to install.'], ['Can I convert many JPG files to PNG at once?', 'Yes. Select or drop several JPG files together. Each one is converted, and you can download them one by one or all together as a ZIP.']] },
  '/png-to-jpg': { priority: 1, primary: 'png to jpg',
    secondary: ['png to jpg converter', 'convert png to jpg', 'png to jpeg', 'png to jpg online free'],
    longtail: ['png to jpg without losing quality', 'png to jpg white background', 'reduce png size by converting to jpg', 'batch convert png to jpg'],
    more: ['convert screenshot to jpg', 'png to jpg small size', 'png to jpg for upload', 'png to jpg on iphone', 'png to jpg on android', 'turn png into jpg', 'png to jpg bulk converter free', 'png to jpg converter for pc'],
    lsi: ['file size', 'lossy compression', 'white background', 'screenshot', 'image quality', 'photo', 'upload limit', 'jpeg quality'],
    faq: [['Can I convert many PNG files to JPG at once?', 'Yes. Select or drop all the PNG files together and download the JPG results one by one or as a single ZIP.'], ["Should I use JPG or PNG for an online form?", "Most forms that ask for a photo want JPG because the files are much smaller. Convert to JPG here, then lower the Quality or choose a Resize option if the form has a size limit."]] },
  '/webp-to-jpg': { priority: 1, primary: 'webp to jpg',
    secondary: ['webp to jpg converter', 'convert webp to jpg', 'webp to jpeg', 'webp to jpg online free'],
    longtail: ['how to open webp image', 'save webp as jpg', 'webp to jpg batch converter', 'webp to jpg high quality'],
    more: ['webp to jpg on iphone', 'webp to jpg on android', 'save webp image as jpg in chrome', 'webp images not opening', 'convert webp to jpg windows', 'turn webp into jpg', 'webp to jpg for instagram', 'download webp as jpg'],
    lsi: ['google image format', 'browser image', 'chrome', 'save image as', 'compatibility', 'photo viewer', 'web image', 'image download'],
    faq: [['How do I save a WebP image as JPG?', 'Save the image from the website to your device, then drop the .webp file here. The JPG is ready to download a few seconds later.'], ["Why does Chrome save images as WebP?", "Many websites serve pictures in WebP because the files are smaller and load faster. When you use Save image as, Chrome keeps the format the website sent. Convert the file here to get an ordinary JPG."]] },
  '/webp-to-png': { priority: 1, primary: 'webp to png',
    secondary: ['webp to png converter', 'convert webp to png', 'webp to png online free'],
    longtail: ['webp to png transparent background', 'save webp as png', 'batch convert webp to png', 'webp to png without losing quality'],
    more: ['webp sticker to png', 'webp logo to png', 'webp to png on iphone', 'webp to png on android', 'turn webp into png', 'webp to png for photoshop', 'webp to png windows'],
    lsi: ['transparency', 'lossless', 'web image', 'browser image', 'sticker', 'logo', 'image editing', 'compatibility'],
    faq: [['Does WebP to PNG keep a transparent background?', 'Yes. PNG supports transparency, so transparent areas of the WebP stay transparent.']] },
  '/jpg-to-webp': { priority: 2, primary: 'jpg to webp',
    secondary: ['jpg to webp converter', 'convert jpg to webp', 'jpeg to webp'],
    longtail: ['convert images to webp for website', 'jpg to webp bulk converter', 'reduce image size for website', 'jpg to webp without losing quality'],
    more: ['convert jpg to webp for wordpress', 'jpg to webp to speed up website', 'jpg to webp quality settings', 'jpg to webp converter free online', 'serve images in next gen formats', 'convert photos to webp', 'jpg to webp for shopify'],
    lsi: ['page speed', 'website performance', 'core web vitals', 'image optimization', 'smaller file size', 'wordpress', 'next gen format', 'lazy loading', 'seo images'] },
  '/png-to-webp': { priority: 2, primary: 'png to webp',
    secondary: ['png to webp converter', 'convert png to webp', 'png to webp online'],
    longtail: ['png to webp keep transparency', 'convert png to webp for wordpress', 'png to webp bulk', 'png to webp lossless'],
    more: ['png to webp for website speed', 'png logo to webp', 'png to webp converter free online', 'png to webp for shopify', 'convert transparent png to webp', 'png to webp quality'],
    lsi: ['transparency', 'alpha channel', 'page speed', 'image optimization', 'website', 'core web vitals', 'smaller images', 'lossless'] },
  '/heic-to-jpg': { priority: 1, primary: 'heic to jpg',
    secondary: ['heic to jpg converter', 'convert heic to jpg', 'heic to jpeg', 'heic to jpg online free'],
    longtail: ['how to open iphone photos on windows', 'convert iphone photos to jpg', 'heic to jpg multiple files', 'heic to jpg without losing quality'],
    more: ['heic to jpg on windows 10', 'heic to jpg on windows 11', 'heic to jpg on android', 'convert icloud photos to jpg', 'iphone photos not opening on pc', 'heic file converter free', 'change iphone photo format to jpg', 'heic to jpg for whatsapp'],
    lsi: ['iphone photos', 'ios camera', 'high efficiency image', 'apple', 'windows photos', 'photo compatibility', 'image codec', 'icloud photos', 'live photo'],
    faq: [['Can I convert many iPhone photos at once?', 'Yes. Select all the HEIC photos together. Each becomes a JPG, and you can download them one by one or all together as a ZIP.'], ["How do I open iPhone photos on Windows 10 or 11?", "Windows only shows HEIC photos after you install the HEIF Image Extensions from the Microsoft Store, and many programs still cannot read them. Converting the photos to JPG here makes them open everywhere, with nothing to install."], ["How do I convert iCloud photos to JPG?", "Download the photos from iCloud to your computer or phone, then select the HEIC files here. Each one becomes a JPG you can download, or get them all together as a ZIP."]] },
  '/heic-to-png': { priority: 2, primary: 'heic to png',
    secondary: ['heic to png converter', 'convert heic to png', 'heic to png online'],
    longtail: ['iphone photo to png', 'heic to png free no sign up', 'convert heic to png on windows'],
    more: ['heic to png on windows', 'heic to png on android', 'iphone image to png for editing', 'heic to png bulk', 'heic image converter png'],
    lsi: ['iphone photos', 'apple image format', 'lossless', 'photo editing', 'windows', 'compatibility', 'ios camera'],
    faq: [["Does HEIC to PNG work on Android and Windows?", "Yes. The page runs in any modern browser, so you can convert iPhone photos on Android phones, Windows PCs and Macs without installing anything."]] },
  '/avif-to-jpg': { priority: 2, primary: 'avif to jpg',
    secondary: ['avif to jpg converter', 'convert avif to jpg', 'avif to jpeg'],
    longtail: ['how to open avif file', 'save avif image as jpg', 'avif to jpg online free'],
    more: ['avif file not opening', 'avif to jpg on windows', 'avif to jpg on android', 'avif to jpg on iphone', 'convert avif image downloaded from chrome', 'turn avif into jpg'],
    lsi: ['av1 image', 'next gen format', 'browser image', 'compatibility', 'photo viewer', 'web image', 'chrome download'] },
  '/avif-to-png': { priority: 3, primary: 'avif to png',
    secondary: ['avif to png converter', 'convert avif to png'],
    longtail: ['avif to png transparent', 'avif to png online free'],
    more: ['avif to png on windows', 'avif to png for photoshop', 'turn avif into png', 'avif image to png free'],
    lsi: ['av1 image', 'transparency', 'lossless', 'web image', 'image editing', 'compatibility'] },
  '/gif-to-webp': { priority: 3, primary: 'gif to webp',
    secondary: ['gif to webp converter', 'convert gif to webp', 'animated gif to webp'],
    longtail: ['reduce gif size with webp', 'animated webp from gif', 'gif to webp keep animation'],
    more: ['convert animated gif to animated webp', 'gif to webp for website', 'make gif smaller with webp', 'gif to webp free online', 'gif to webp keep transparency'],
    lsi: ['animation', 'animated image', 'frames', 'file size', 'website speed', 'loop', 'web animation'] },
  '/svg-to-png': { priority: 1, primary: 'svg to png',
    secondary: ['svg to png converter', 'convert svg to png', 'svg to png online'],
    longtail: ['svg to png transparent background', 'svg to png high resolution', 'svg to png free no sign up'],
    more: ['svg logo to png', 'svg icon to png', 'convert svg file to png image', 'svg to png for powerpoint', 'svg to png for word', 'svg to png for social media', 'turn svg into png'],
    lsi: ['vector graphics', 'raster image', 'logo', 'icon', 'scalable', 'transparent background', 'resolution', 'illustrator'],
    faq: [['Does SVG to PNG keep a transparent background?', 'Yes. Areas of the SVG without a fill stay transparent in the PNG.']] },
  '/png-to-ico': { priority: 2, primary: 'png to ico',
    secondary: ['png to favicon', 'png to ico converter', 'convert png to ico', 'favicon generator from png'],
    longtail: ['make favicon from png', 'png to ico for windows icon', 'png to ico multiple sizes'],
    more: ['create favicon ico from png', 'png to ico 16x16 32x32 48x48', 'png to ico for website', 'make windows icon from png', 'png to favicon free', 'convert logo to favicon'],
    lsi: ['favicon', 'website icon', 'browser tab icon', 'windows icon', 'icon sizes', '16x16', '32x32', 'transparent icon'] },
  '/tiff-to-jpg': { priority: 2, primary: 'tiff to jpg',
    secondary: ['tif to jpg', 'tiff to jpg converter', 'convert tiff to jpg', 'tiff to jpeg'],
    longtail: ['convert scanned tiff to jpg', 'tiff to jpg online free', 'reduce tiff file size'],
    more: ['tif to jpg online free', 'convert scanned tif to jpg', 'tiff to jpg for email', 'tiff to jpg high quality', 'turn tiff into jpg', 'tiff to jpg bulk converter'],
    lsi: ['scanner', 'scanned document', 'high resolution', 'print', 'photography', 'file size', 'image archive'] },
  '/bmp-to-jpg': { priority: 3, primary: 'bmp to jpg',
    secondary: ['bmp to jpg converter', 'convert bmp to jpg', 'bmp to jpeg'],
    longtail: ['bmp to jpg online free', 'reduce bmp file size'],
    more: ['convert paint image to jpg', 'bitmap to jpg', 'bmp to jpg bulk', 'bmp to jpg for email', 'turn bmp into jpg'],
    lsi: ['bitmap', 'paint', 'windows image', 'uncompressed', 'file size', 'photo'] },
  '/jfif-to-jpg': { priority: 2, primary: 'jfif to jpg',
    secondary: ['jfif to jpg converter', 'convert jfif to jpg', 'jfif to jpeg'],
    longtail: ['what is jfif file', 'change jfif to jpg', 'jfif to jpg online free'],
    more: ['why do my images save as jfif', 'jfif to jpg on windows', 'jfif to jpg on android', 'jfif to jpg for upload', 'jfif to jpeg online free', 'change jfif extension to jpg'],
    lsi: ['jpeg file interchange format', 'file extension', 'chrome download', 'windows', 'photo upload', 'image viewer'],
    faq: [["Why do my images save as JFIF?", "A setting on some Windows PCs makes browsers save JPEG pictures with the .jfif ending. The picture inside is ordinary JPEG. Convert it here, or type .jpg at the end of the name when you save."]] },

  // ---------- PDF ----------
  '/jpg-to-pdf': { priority: 1, primary: 'jpg to pdf',
    secondary: ['jpg to pdf converter', 'convert jpg to pdf', 'image to pdf', 'jpeg to pdf'],
    longtail: ['photo to pdf online free', 'jpg to pdf without watermark', 'convert jpg to pdf on phone', 'jpg to pdf without changing size'],
    more: ['jpg to pdf for online form', 'photo to pdf for upload', 'convert id card photo to pdf', 'convert certificate jpg to pdf', 'jpg to pdf for email', 'jpg to pdf on iphone', 'jpg to pdf on android', 'convert scanned jpg to pdf'],
    lsi: ['document', 'scan', 'photo', 'print', 'a4', 'send by email', 'attachment', 'upload form', 'pdf file'],
    faq: [['Can I convert JPG to PDF on my phone?', 'Yes. Open this page in your phone browser, tap Select File and choose photos from your gallery. Each photo becomes a PDF you can download.'], ["How do I convert a photo to PDF for an online form?", "Select the photo here and download the PDF. If the form has a size limit, compress the JPG first with a lower Quality or a Resize option, then convert it to PDF."]] },
  '/png-to-pdf': { priority: 2, primary: 'png to pdf',
    secondary: ['png to pdf converter', 'convert png to pdf', 'image to pdf'],
    longtail: ['screenshot to pdf', 'png to pdf multiple files', 'png to pdf online free'],
    more: ['convert screenshot to pdf on phone', 'png to pdf for email', 'png to pdf on iphone', 'png to pdf on android', 'png image to pdf free', 'turn png into pdf'],
    lsi: ['screenshot', 'document', 'print', 'attachment', 'image', 'pdf file', 'share'] },
  '/pdf-to-jpg': { priority: 1, primary: 'pdf to jpg',
    secondary: ['pdf to jpg converter', 'convert pdf to jpg', 'pdf to image', 'pdf to jpeg'],
    longtail: ['pdf to jpg high quality', 'save pdf pages as images', 'pdf to jpg all pages', 'pdf to jpg online free'],
    more: ['pdf to jpg for whatsapp', 'pdf to jpg for instagram', 'pdf to jpg on iphone', 'pdf to jpg on android', 'pdf to jpg converter for pc free', 'convert each pdf page to image', 'pdf to jpg 150 dpi'],
    lsi: ['pdf pages', 'image', 'resolution', 'dpi', 'slides', 'share on whatsapp', 'presentation', 'zip'],
    faq: [['Are all pages converted?', 'Yes. Every page of the PDF becomes its own JPG image, and a PDF with several pages downloads as a ZIP of images.'], ["How do I send PDF pages on WhatsApp as pictures?", "Convert the PDF to JPG here. A one-page PDF gives a single JPG; a longer PDF gives a ZIP with one JPG per page. Open the ZIP on your phone and share the pictures you need."]] },
  '/pdf-to-png': { priority: 2, primary: 'pdf to png',
    secondary: ['pdf to png converter', 'convert pdf to png', 'pdf to image'],
    longtail: ['pdf to png high resolution', 'pdf page to png', 'pdf to png online free'],
    more: ['pdf to png on iphone', 'pdf to png on android', 'convert each pdf page to png', 'pdf to png for presentation', 'pdf to png free'],
    lsi: ['pdf pages', 'image', 'transparent', 'resolution', 'dpi', 'slides', 'lossless'] },
  '/pdf-to-docx': { priority: 1, primary: 'pdf to word',
    secondary: ['pdf to docx', 'pdf to word converter', 'convert pdf to word', 'pdf to doc'],
    longtail: ['pdf to word editable', 'pdf to word free without email', 'convert pdf to word keep formatting', 'pdf to word online free'],
    more: ['how to edit a pdf in word', 'pdf to word on iphone', 'pdf to word on android', 'pdf to word converter for pc free', 'pdf to word without software', 'convert pdf resume to word', 'convert pdf to word document free', 'pdf to doc online'],
    lsi: ['microsoft word', 'editable document', 'text', 'formatting', 'layout', 'fonts', 'tables', 'ocr', 'edit pdf'],
    faq: [['Can I edit the Word file?', 'Yes. Text from a PDF made on a computer becomes editable text in the DOCX. The layout is rebuilt with text boxes, so complex pages may need some tidying. A scanned PDF only holds pictures of pages, so its text cannot be edited.'], ['Do I need to give my email?', 'No. There is no sign-up and no email. The Word file downloads straight from this page.'], ["Can I convert PDF to Word on my phone?", "Yes. Open this page in your phone browser, select the PDF and download the DOCX. You can edit it in Microsoft Word, Google Docs or WPS Office on the phone."]] },
  '/docx-to-pdf': { priority: 1, primary: 'word to pdf',
    secondary: ['docx to pdf', 'word to pdf converter', 'convert word to pdf', 'doc to pdf'],
    longtail: ['word to pdf online free', 'convert docx to pdf keep formatting', 'save word document as pdf', 'word to pdf without watermark'],
    more: ['convert resume to pdf', 'convert assignment to pdf', 'word to pdf on iphone', 'word to pdf on android', 'word to pdf without microsoft office', 'word to pdf for submission', 'docx to pdf converter free', 'word to pdf with hyperlinks'],
    lsi: ['microsoft word', 'document', 'formatting', 'fonts', 'print', 'resume', 'assignment', 'share', 'pdf file'],
    faq: [['Does the PDF have a watermark?', 'No. The PDF contains only your document, with no watermark or added pages.'], ["Can I convert Word to PDF without Microsoft Office?", "Yes. The conversion happens on our server, so you only need a browser. It works for resumes, assignments and letters on a computer or a phone."]] },
  '/doc-to-pdf': { priority: 2, primary: 'doc to pdf',
    secondary: ['doc to pdf converter', 'convert doc to pdf', 'old word file to pdf'],
    longtail: ['doc to pdf online free', 'convert word 97-2003 to pdf'],
    more: ['doc to pdf without word', 'doc to pdf on android', 'doc to pdf on iphone', 'convert old word file to pdf free', 'doc file to pdf online'],
    lsi: ['word 97-2003', 'old word document', 'formatting', 'print', 'office', 'legacy format'] },
  '/doc-to-docx': { priority: 3, primary: 'doc to docx',
    secondary: ['doc to docx converter', 'convert doc to docx'],
    longtail: ['open old word documents', 'doc to docx online free'],
    more: ['remove compatibility mode word', 'doc to docx without word', 'upgrade doc to docx', 'doc to docx online free', 'open doc file in new word'],
    lsi: ['word 97-2003', 'compatibility mode', 'microsoft word', 'office', 'legacy format', 'upgrade document'] },
  '/xlsx-to-pdf': { priority: 2, primary: 'excel to pdf',
    secondary: ['xlsx to pdf', 'excel to pdf converter', 'convert excel to pdf'],
    longtail: ['excel to pdf fit to page', 'excel to pdf online free', 'save spreadsheet as pdf'],
    more: ['excel invoice to pdf', 'excel sheet to pdf', 'xlsx to pdf without excel', 'excel to pdf on android', 'excel to pdf on iphone', 'excel to pdf converter free', 'spreadsheet to pdf online'],
    lsi: ['spreadsheet', 'microsoft excel', 'worksheet', 'table', 'invoice', 'report', 'print area', 'page layout'],
    faq: [["Can I convert Excel to PDF without Excel?", "Yes. Select the XLSX file here and download the PDF. You do not need Microsoft Excel on your computer or phone."]] },
  '/pptx-to-pdf': { priority: 2, primary: 'ppt to pdf',
    secondary: ['pptx to pdf', 'powerpoint to pdf', 'convert ppt to pdf'],
    longtail: ['powerpoint to pdf online free', 'presentation to pdf', 'pptx to pdf keep fonts'],
    more: ['powerpoint slides to pdf', 'ppt to pdf without powerpoint', 'ppt to pdf on android', 'ppt to pdf on iphone', 'convert presentation to pdf for email', 'pptx to pdf converter free', 'lecture slides to pdf'],
    lsi: ['presentation', 'slides', 'microsoft powerpoint', 'handout', 'print', 'share', 'lecture'],
    faq: [["Can I convert PowerPoint to PDF without PowerPoint?", "Yes. Select the PPTX file here and download the PDF, with one slide per page. You do not need PowerPoint installed."]] },
  '/pdf-to-txt': { priority: 3, primary: 'pdf to text',
    secondary: ['pdf to txt', 'pdf to text converter', 'extract text from pdf'],
    longtail: ['copy text from pdf', 'pdf to txt online free'],
    more: ['pdf to notepad', 'extract all text from pdf', 'pdf to txt free', 'convert pdf to plain text file', 'get text out of pdf'],
    lsi: ['plain text', 'extract text', 'copy text', 'notepad', 'text file', 'searchable pdf'] },
  '/epub-to-pdf': { priority: 2, primary: 'epub to pdf',
    secondary: ['epub to pdf converter', 'convert epub to pdf'],
    longtail: ['ebook to pdf', 'epub to pdf online free', 'print epub book'],
    more: ['epub to pdf for printing', 'epub book to pdf free', 'epub to pdf on android', 'epub to pdf on iphone', 'read epub as pdf', 'convert ebook to pdf free'],
    lsi: ['ebook', 'e-reader', 'book', 'print', 'kindle', 'reading', 'chapters'] },

  // ---------- Spreadsheets ----------
  '/csv-to-xlsx': { priority: 2, primary: 'csv to excel',
    secondary: ['csv to xlsx', 'csv to excel converter', 'convert csv to excel'],
    longtail: ['open csv in excel correctly', 'csv to xlsx online free'],
    more: ['csv to excel without breaking columns', 'csv to xlsx free', 'open csv file as excel', 'convert csv data to spreadsheet', 'csv to excel on mac'],
    lsi: ['spreadsheet', 'comma separated values', 'microsoft excel', 'data', 'columns', 'rows', 'table'] },
  '/xlsx-to-csv': { priority: 2, primary: 'excel to csv',
    secondary: ['xlsx to csv', 'excel to csv converter', 'convert excel to csv'],
    longtail: ['xlsx to csv online free', 'save excel as csv utf-8'],
    more: ['excel to csv for import', 'excel to csv without excel', 'xlsx to csv free', 'convert spreadsheet to csv', 'excel sheet to csv file'],
    lsi: ['spreadsheet', 'comma separated values', 'data export', 'import', 'database', 'columns', 'utf-8'] },

  // ---------- Video ----------
  '/mp4-to-mp3': { priority: 1, primary: 'mp4 to mp3',
    secondary: ['mp4 to mp3 converter', 'convert mp4 to mp3', 'video to mp3', 'video to audio converter'],
    longtail: ['extract audio from video', 'mp4 to mp3 high quality', 'mp4 to mp3 online free', 'video to mp3 without software'],
    more: ['convert video to song', 'mp4 to mp3 on iphone', 'mp4 to mp3 on android', 'mp4 to mp3 converter for pc free', 'video to mp3 converter free', 'get audio from mp4', 'mp4 to audio online', 'save sound from video'],
    lsi: ['audio', 'music', 'song', 'soundtrack', 'bitrate', 'audio quality', 'extract sound', 'video file'],
    faq: [['What quality is the MP3?', 'The MP3 uses high-quality variable bitrate encoding, around 190 kbps on average, which sounds the same as the video for normal listening.'], ['Do I need to install software?', 'No. Everything happens in your browser and on our server, on a computer or a phone.'], ["Can I convert MP4 to MP3 on iPhone or Android?", "Yes. Open this page in your phone browser, select the video and download the MP3. On iPhone the file is saved in the Files app."]] },
  '/mov-to-mp4': { priority: 1, primary: 'mov to mp4',
    secondary: ['mov to mp4 converter', 'convert mov to mp4', 'iphone video to mp4'],
    longtail: ['mov to mp4 online free', 'mov to mp4 without losing quality', 'convert quicktime to mp4'],
    more: ['iphone video to mp4 for windows', 'mov to mp4 on windows', 'mov to mp4 on android', 'mov to mp4 for youtube', 'mov to mp4 for whatsapp', 'mov to mp4 free converter', 'turn mov into mp4'],
    lsi: ['quicktime', 'iphone video', 'video format', 'h.264', 'compatibility', 'windows', 'android', 'video quality'],
    faq: [['Does it work with iPhone videos?', 'Yes. iPhone videos are saved as MOV files, and converting them to MP4 makes them easy to play on Windows, Android and most websites.'], ["Why will my iPhone video not play on Windows?", "iPhone videos are MOV files, often recorded in HEVC, which some Windows PCs cannot play without an extra codec. The MP4 made here uses H.264, which Windows, Android and every browser can play."]] },
  '/mkv-to-mp4': { priority: 2, primary: 'mkv to mp4',
    secondary: ['mkv to mp4 converter', 'convert mkv to mp4'],
    longtail: ['mkv to mp4 online free', 'mkv to mp4 without losing quality', 'play mkv on phone'],
    more: ['mkv to mp4 for tv', 'mkv to mp4 for iphone', 'mkv to mp4 for android', 'mkv movie to mp4', 'mkv to mp4 free converter', 'turn mkv into mp4'],
    lsi: ['matroska', 'video container', 'subtitles', 'h.264', 'movie', 'compatibility', 'tv', 'phone'],
    faq: [["Can I play the MP4 on a TV or phone?", "Yes. The MP4 uses H.264 video and AAC audio, which smart TVs, iPhones, Android phones and browsers all play. Subtitle tracks from the MKV are not carried over."]] },
  '/webm-to-mp4': { priority: 2, primary: 'webm to mp4',
    secondary: ['webm to mp4 converter', 'convert webm to mp4'],
    longtail: ['webm to mp4 online free', 'screen recording webm to mp4'],
    more: ['webm to mp4 for whatsapp', 'webm to mp4 for instagram', 'webm to mp4 on iphone', 'webm to mp4 free converter', 'turn webm into mp4', 'convert browser recording to mp4'],
    lsi: ['web video', 'browser recording', 'vp9', 'h.264', 'screen recording', 'compatibility'] },
  '/avi-to-mp4': { priority: 2, primary: 'avi to mp4',
    secondary: ['avi to mp4 converter', 'convert avi to mp4'],
    longtail: ['avi to mp4 online free', 'old video to mp4'],
    more: ['avi to mp4 for phone', 'avi to mp4 for youtube', 'avi to mp4 smaller size', 'avi to mp4 free converter', 'turn avi into mp4'],
    lsi: ['old video', 'camcorder', 'video format', 'h.264', 'compatibility', 'file size'] },
  '/mp4-to-gif': { priority: 2, primary: 'mp4 to gif',
    secondary: ['video to gif', 'mp4 to gif converter', 'convert mp4 to gif'],
    longtail: ['make gif from video', 'video to gif online free', 'mp4 to gif high quality'],
    more: ['make gif from mp4', 'convert video clip to gif', 'mp4 to gif for discord', 'mp4 to gif for twitter', 'video to gif on iphone', 'video to gif on android', 'short video to gif'],
    lsi: ['animation', 'animated image', 'meme', 'reaction gif', 'frames', 'loop', 'clip'],
    faq: [["How big will the GIF be?", "The GIF is made at 12 frames per second and at most 480 pixels wide, which keeps it small enough for chats and websites. Short clips of a few seconds work best."]] },
  '/gif-to-mp4': { priority: 3, primary: 'gif to mp4',
    secondary: ['gif to mp4 converter', 'convert gif to mp4', 'gif to video'],
    longtail: ['gif to mp4 for instagram', 'gif to mp4 online free'],
    more: ['gif to mp4 for twitter', 'gif to mp4 for whatsapp status', 'gif to video converter free', 'turn gif into video', 'gif to mp4 smaller file'],
    lsi: ['animation', 'video', 'loop', 'social media', 'file size', 'meme'] },

  // ---------- Audio ----------
  '/wav-to-mp3': { priority: 2, primary: 'wav to mp3',
    secondary: ['wav to mp3 converter', 'convert wav to mp3'],
    longtail: ['wav to mp3 high quality', 'wav to mp3 online free', 'reduce wav file size'],
    more: ['wav to mp3 converter free', 'convert recording to mp3', 'wav to mp3 on iphone', 'wav to mp3 on android', 'turn wav into mp3', 'wav to mp3 small size'],
    lsi: ['audio', 'recording', 'music', 'bitrate', 'uncompressed audio', 'file size', 'sound quality'],
    faq: [["How much smaller is the MP3 than the WAV?", "Usually around 7 to 8 times smaller, because WAV stores uncompressed audio and MP3 uses high-quality compression."]] },
  '/m4a-to-mp3': { priority: 2, primary: 'm4a to mp3',
    secondary: ['m4a to mp3 converter', 'convert m4a to mp3'],
    longtail: ['iphone voice memo to mp3', 'm4a to mp3 online free', 'whatsapp audio to mp3'],
    more: ['voice memo to mp3', 'iphone recording to mp3', 'm4a to mp3 on android', 'm4a to mp3 on windows', 'm4a to mp3 converter free', 'turn m4a into mp3'],
    lsi: ['voice memo', 'voice recording', 'apple audio', 'aac', 'iphone recording', 'music', 'audio file'],
    faq: [["How do I convert an iPhone voice memo to MP3?", "Share the voice memo from the Voice Memos app and save it to Files. The file is an M4A; select it here and download the MP3."]] },
  '/flac-to-mp3': { priority: 3, primary: 'flac to mp3',
    secondary: ['flac to mp3 converter', 'convert flac to mp3'],
    longtail: ['flac to mp3 high quality', 'flac to mp3 online free'],
    more: ['flac to mp3 converter free', 'flac album to mp3', 'flac to mp3 for phone', 'flac to mp3 smaller size', 'turn flac into mp3'],
    lsi: ['lossless audio', 'music', 'hi-res audio', 'bitrate', 'file size', 'album'] },
  '/ogg-to-mp3': { priority: 3, primary: 'ogg to mp3',
    secondary: ['ogg to mp3 converter', 'convert ogg to mp3', 'opus to mp3'],
    longtail: ['whatsapp voice note to mp3', 'ogg to mp3 online free'],
    more: ['whatsapp audio to mp3', 'telegram voice message to mp3', 'opus file to mp3', 'ogg to mp3 converter free', 'turn ogg into mp3', 'ogg to mp3 on android'],
    lsi: ['voice note', 'opus', 'vorbis', 'whatsapp audio', 'telegram voice', 'audio file'],
    faq: [["How do I convert a WhatsApp voice note to MP3?", "Save the voice note from the chat to your phone. It is usually an OGG or OPUS file; select it here and download the MP3, which plays on any device."]] },

  // ---------- Ebooks ----------
  '/epub-to-mobi': { priority: 3, primary: 'epub to mobi',
    secondary: ['epub to mobi converter', 'convert epub to mobi', 'epub to kindle'],
    longtail: ['epub to mobi online free', 'read epub on kindle'],
    more: ['epub to kindle format', 'epub to mobi free', 'convert ebook for kindle', 'epub to mobi for old kindle'],
    lsi: ['kindle', 'ebook', 'e-reader', 'amazon', 'book', 'reading'] },
  '/mobi-to-epub': { priority: 3, primary: 'mobi to epub',
    secondary: ['mobi to epub converter', 'convert mobi to epub'],
    longtail: ['kindle book to epub', 'mobi to epub online free'],
    more: ['mobi to epub for apple books', 'mobi to epub for kobo', 'mobi to epub free', 'kindle file to epub'],
    lsi: ['kindle', 'ebook', 'e-reader', 'kobo', 'apple books', 'reading'] },

  // ---------- Fonts ----------
  '/ttf-to-woff2': { priority: 3, primary: 'ttf to woff2',
    secondary: ['ttf to woff2 converter', 'convert ttf to woff2', 'web font converter'],
    longtail: ['convert font for website', 'ttf to woff2 online free'],
    more: ['convert font for css', 'ttf to woff2 for website', 'ttf to woff2 free', 'make web font from ttf', 'self host fonts woff2'],
    lsi: ['web font', 'font file', 'css', '@font-face', 'website', 'page speed', 'typography'] },
  '/woff2-to-ttf': { priority: 3, primary: 'woff2 to ttf',
    secondary: ['woff2 to ttf converter', 'convert woff2 to ttf'],
    longtail: ['install web font on windows', 'woff2 to ttf online free'],
    more: ['install woff2 font on windows', 'woff2 to ttf for word', 'woff2 to ttf free', 'convert web font to desktop font'],
    lsi: ['web font', 'desktop font', 'install font', 'font file', 'windows', 'mac'] },

  // ---------- Compress ----------
  '/compress-jpg': { priority: 1, primary: 'compress jpg',
    secondary: ['jpg compressor', 'compress jpeg', 'reduce jpg size', 'compress image'],
    longtail: ['compress jpg to 100kb', 'compress jpg to 50kb', 'reduce photo size online', 'compress image without losing quality'],
    more: ['compress jpg to 200kb', 'compress jpg to 20kb', 'compress photo for online form', 'reduce image size in kb', 'compress jpg for email', 'compress jpg for website', 'reduce photo size without losing quality', 'compress image on iphone'],
    lsi: ['file size', 'kb', 'image quality', 'resize', 'photo', 'upload limit', 'optimize', 'pixels'],
    faq: [['How do I compress a JPG to 100 KB or 50 KB?', 'Open the file settings, lower the Quality and choose a Resize option such as 1280 or 800 pixels. The list shows the new size of every file; if it is still too big, change the settings and compress again.'], ["How do I reduce a photo for an online form?", "Open the file settings, choose Max 800px under Resize and a Quality around 60, then check the new size in the list. Most forms that ask for under 100 or 200 KB accept the result; lower the settings and compress again if needed."]] },
  '/compress-png': { priority: 2, primary: 'compress png',
    secondary: ['png compressor', 'reduce png size', 'png optimizer'],
    longtail: ['compress png without losing quality', 'compress png keep transparency', 'reduce png file size online'],
    more: ['compress png to 100kb', 'compress png for website', 'reduce png size without losing quality', 'compress transparent png', 'png size reducer free', 'optimize png images'],
    lsi: ['file size', 'transparency', 'image quality', 'optimize', 'website', 'colors', 'palette', 'kb'],
    faq: [["Does compressing PNG keep transparency?", "Yes. Transparent areas stay transparent. The colours are reduced to a smaller palette, which makes the file smaller."]] },
  '/compress-pdf': { priority: 1, primary: 'compress pdf',
    secondary: ['pdf compressor', 'reduce pdf size', 'pdf size reducer'],
    longtail: ['compress pdf to 1mb', 'compress pdf for email', 'reduce pdf size online free', 'compress pdf without losing quality'],
    more: ['make pdf smaller', 'shrink pdf file size', 'compress pdf for online form', 'reduce scanned pdf size', 'compress pdf for whatsapp', 'pdf size reducer free', 'compress pdf on iphone', 'compress pdf on android'],
    lsi: ['file size', 'mb', 'email attachment', 'upload limit', 'scanned pdf', 'images', 'dpi', 'document'],
    faq: [['How do I make a PDF small enough for email?', 'Upload it here. Images inside the PDF are reduced to 150 dpi, which makes scanned and photo-heavy PDFs much smaller. PDFs that are mostly text are often small already and shrink less.'], ["Can I compress a scanned PDF?", "Yes, and scanned PDFs usually shrink the most, because they are made of large page images that are reduced to 150 dpi. The list shows the before and after size."]] },
  '/compress-webp': { priority: 3, primary: 'compress webp',
    secondary: ['webp compressor', 'reduce webp size'],
    longtail: ['compress webp online free'],
    more: ['reduce webp file size', 'compress webp images for website', 'webp size reducer free'],
    lsi: ['file size', 'website', 'image quality', 'optimize', 'kb'] },
  '/compress-gif': { priority: 2, primary: 'compress gif',
    secondary: ['gif compressor', 'reduce gif size'],
    longtail: ['compress gif for discord', 'reduce gif file size online'],
    more: ['make gif smaller', 'reduce animated gif size', 'gif size reducer free', 'compress gif for email'],
    lsi: ['animation', 'file size', 'frames', 'colors', 'upload limit', 'kb'] },
  '/compress-avif': { priority: 3, primary: 'compress avif',
    secondary: ['avif compressor', 'reduce avif size'],
    longtail: ['compress avif online free'],
    more: ['reduce avif file size', 'avif size reducer free'],
    lsi: ['file size', 'next gen format', 'image quality', 'website'] },
  '/compress-tiff': { priority: 3, primary: 'compress tiff',
    secondary: ['tiff compressor', 'reduce tiff size'],
    longtail: ['compress scanned tiff online'],
    more: ['reduce tiff file size', 'tiff size reducer free', 'compress tiff for email'],
    lsi: ['scanned image', 'file size', 'print', 'high resolution'] },

  // ---------- Categories ----------
  '/image-converter': { priority: 1, primary: 'image converter',
    secondary: ['photo converter', 'image format converter', 'convert image online'],
    longtail: ['free image converter online', 'convert image to jpg', 'convert image to png'],
    more: ['convert any image to jpg', 'online photo format converter', 'image converter for mobile', 'batch image converter free', 'change image format online'],
    lsi: ['photo', 'jpg', 'png', 'webp', 'heic', 'file format', 'image quality', 'resize'] },
  '/video-converter': { priority: 1, primary: 'video converter',
    secondary: ['online video converter', 'convert video online', 'video format converter'],
    longtail: ['free video converter no watermark', 'convert video to mp4 online'],
    more: ['convert any video to mp4', 'video converter for mobile', 'change video format online', 'free video format converter online'],
    lsi: ['mp4', 'mov', 'mkv', 'video format', 'codec', 'resolution', 'file size'] },
  '/audio-converter': { priority: 2, primary: 'audio converter',
    secondary: ['online audio converter', 'convert audio online', 'mp3 converter'],
    longtail: ['convert audio to mp3 online free', 'free audio converter no sign up'],
    more: ['convert any audio to mp3', 'change audio format online', 'audio converter for mobile', 'free audio format converter'],
    lsi: ['mp3', 'wav', 'm4a', 'music', 'bitrate', 'sound quality', 'recording'] },
  '/document-converter': { priority: 2, primary: 'document converter',
    secondary: ['online document converter', 'convert documents online', 'word converter'],
    longtail: ['convert document to pdf online free'],
    more: ['convert word documents online free', 'change document format online', 'docx odt rtf converter'],
    lsi: ['word', 'docx', 'odt', 'rtf', 'text', 'office', 'pdf'] },
  '/pdf-converter': { priority: 1, primary: 'pdf converter',
    secondary: ['online pdf converter', 'convert pdf', 'pdf converter free'],
    longtail: ['pdf converter without watermark', 'convert pdf to word excel jpg'],
    more: ['free pdf converter online', 'convert pdf to any format', 'pdf converter for mobile', 'convert files to pdf online'],
    lsi: ['word', 'jpg', 'excel', 'powerpoint', 'document', 'pdf file', 'edit'] },
  '/ebook-converter': { priority: 3, primary: 'ebook converter',
    secondary: ['epub converter', 'online ebook converter'],
    longtail: ['convert ebook to pdf', 'convert ebook for kindle'],
    more: ['convert ebook format online', 'ebook converter for kindle free', 'epub mobi converter online'],
    lsi: ['epub', 'mobi', 'kindle', 'e-reader', 'book', 'pdf'] },
  '/font-converter': { priority: 3, primary: 'font converter',
    secondary: ['web font converter', 'ttf converter', 'woff converter'],
    longtail: ['convert font to woff2 online'],
    more: ['convert font file online', 'web font converter free', 'ttf otf woff converter'],
    lsi: ['ttf', 'otf', 'woff', 'woff2', 'web font', 'typography'] },
};
